name: ci-nodejs-workflow
on:
  pull_request:
    branches:
      - master
jobs: 
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
      - run: npm install
      - run: npm test